/**
 * Typed bindings for this Worker.
 *
 * `DB`                — D1 binding, declared in `wrangler.toml`.
 * `ANTHROPIC_API_KEY` — Secret. Set with `wrangler secret put ANTHROPIC_API_KEY`.
 *                       Locally, place in `.dev.vars`.
 * `PIN_HASH`          — Secret. SHA-256 hex digest of the user's PIN.
 *                       Generated by the operator: `echo -n PIN | shasum -a 256`.
 * `SESSION_SECRET`    — Secret. 32 random hex bytes used to HMAC session cookies.
 *                       Generated by the operator: `openssl rand -hex 32`.
 *
 * All three secrets are required at request time. Routes that touch them
 * surface clean error responses if any are missing (and the structured
 * logger redacts the values defensively).
 */
export interface Env {
  DB: D1Database;
  ANTHROPIC_API_KEY: string;
  PIN_HASH: string;
  SESSION_SECRET: string;
}
